apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-client
  template:
    metadata:
      labels:
        app: react-client
    spec:
      containers:
      - name: react-client
        image: react-client:v1.0  # Use local image
        imagePullPolicy: Never
        
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: react-client
spec:
  selector:
    app: react-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  # No NodePort here for local forwarding

