apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-producer-app
  labels:
    app: ms-producer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-producer-app
  template:
    metadata:
      labels:
        app: ms-producer-app
    spec:
      containers:
        - name: ms-producer-app
          image: ms-producer-app:v1.0
          ports:
            - containerPort: 8080  # Match producer port 8080
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092" 
---
apiVersion: v1
kind: Service
metadata:
  name: ms-producer-app
spec:
  ports:
    - port: 8080  # Expose service on port 8080
  selector:
    app: ms-producer-app
